version: '3.9'

services:
  mongodb:
    image: 'docker.io/bitnami/mongodb:5.0-debian-10'
    restart: always
    environment:
      - MONGODB_ROOT_PASSWORD=docker
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=docker
      - MONGODB_DATABASE=weba
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local
